#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
npm run prettier:check ||
(
    echo 'Prettier check Failed. Run npm run prettier:write, add changes and try commit again.';
    false;
)

echo '✅ Your code style is looking good, checking Typescript now ...'
# Check tsconfig standards
npm run check-types ||
(
    echo 'Typescript checks failed. Make the changes required above.'
    false;
)

echo '✅ No Typescript error, congrats ! Checking ESLint'

# Check ESLint Standards
npm run check-lint ||
(
        echo 'ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false;
)

echo '✅ No ESLint error(s), congrats ! Finally checking for unused exports'

# # Check if unused exports are present
# npm run check-unused-exports ||
# (
#         echo 'Unused exports checks failed. Make the required changes listed above, add changes and try to commit again.'
#         false;
# )

# If everything passes... Now we can commit
echo '✅ Everything looks perfect. Commiting ...'
